"use client";

import { useMemo, useState } from "react";

const scenarios = [
 ["Mahal.","Budget, value, scope, comparison, timing, or uncertainty.","Boleh saya faham, bahagian mana yang membuatkan investment ini terasa tinggi?","Actual barrier.","Answer only the barrier supported by the buyer's response.","Adakah itu yang paling menghalang sekarang?","Proceed / adjust / pause / exit"],
 ["Nak fikir dulu.","Need more information, uncertainty, timing, authority, or polite delay.","Boleh saya tahu apa yang anda masih perlu fikirkan?","Specific unresolved issue.","Clarify the issue rather than immediately adding pressure.","Jika perkara itu jelas, adakah ada perkara lain?","Follow-up / decision / exit"],
 ["Saya nak compare.","Comparing price, scope, quality, proof, terms, or alternatives.","Apa yang paling penting untuk anda bandingkan?","Decision criteria.","Help compare relevant criteria transparently.","Adakah kriteria itu sudah cukup jelas?","Choose / more info / pause"],
 ["Berapa harga?","Could be a straightforward price request or a scope-dependent question.","If scope is clear, answer. If not, ask the minimum context needed.","Scope / fit / quantity / relevant variables.","State price clearly when context is sufficient.","Confirm fit or next question.","Quote / qualify / continue"],
 ["Quotation silence","Unknown: busy, timing, uncertainty, comparison, authority, or no interest.","Adakah quotation ini masih relevan untuk anda?","Current status.","Use purpose-led follow-up; do not invent a reason.","Invite a clear status.","Follow-up / re-enter / close loop"],
 ["Saya kena tanya boss/partner.","Decision authority or stakeholder alignment is incomplete.","Siapa lagi yang perlu terlibat dan apa yang mereka perlukan untuk membuat keputusan?","Authority + criteria.","Facilitate the decision process without bypassing the stakeholder.","Confirm next decision step.","Include stakeholder / follow-up"],
 ["Bukan sekarang.","Timing genuinely not right or priority is low.","Apa yang akan menentukan masa yang lebih sesuai?","Trigger / timing.","Respect timing and define a relevant re-entry point if appropriate.","Confirm timing or condition.","Follow-up / reactivation / exit"],
 ["Clear “No”","Buyer has decided not to proceed.","Faham. Boleh saya tahu jika ada faktor utama yang mempengaruhi keputusan?","Optional learning only.","Respect the decision. Do not pressure.","Acknowledge.","Graceful exit / future permission"]
] as const;

export default function ObjectionPlaybookPage(){
 const [selected,setSelected]=useState(0);
 const [statement,setStatement]=useState("");
 const [meaning,setMeaning]=useState("");
 const [question,setQuestion]=useState("");
 const [answer,setAnswer]=useState("");
 const [barrier,setBarrier]=useState("");
 const [response,setResponse]=useState("");
 const [confirmation,setConfirmation]=useState("");
 const [nextStep,setNextStep]=useState("");
 const s=scenarios[selected];
 const diagnosisReady=Boolean(question.trim()&&answer.trim()&&barrier.trim());
 const derived=useMemo(()=>diagnosisReady?"Answer the actual barrier, then confirm whether it is resolved.":"Capture evidence before choosing a response.",[diagnosisReady]);
 return <main className="container" style={{padding:"28px 0 60px"}}>
  <header className="app-header"><div><div className="brand" style={{fontSize:24}}>BROS SELL™</div><div className="muted">Objection Playbook</div></div><div style={{display:"flex",gap:8}}><a className="btn secondary" href="/app">Analyzer</a><a className="btn secondary" href="/app/resources">Resources</a></div></header>
  <section className="hero"><p className="muted">DIAGNOSE → CLARIFY → ANSWER → CONFIRM</p><h1>Objection Playbook</h1><p className="muted hero-copy">Objection ≠ Enemy. Diagnose the reason behind the statement before deciding how to respond.</p></section>
  <section className="card resource-section"><div className="eyebrow">COMMON SCENARIOS</div><div className="resource-grid">{scenarios.map((x,i)=><button type="button" className={selected===i?"resource-card refined":"resource-card"} key={x[0]} onClick={()=>{setSelected(i);setStatement(x[0]);setMeaning(x[1]);setQuestion(x[2]);setBarrier(x[3]);setResponse(x[4]);setConfirmation(x[5]);setNextStep(x[6]);}}><small className="muted">SCENARIO {i+1}</small><h2>{x[0]}</h2><p className="muted">{x[1]}</p></button>)}</div></section>
  <section className="card resource-section"><div className="eyebrow">DIAGNOSE</div><div className="resource-grid"><label className="field-label"><span>Exact buyer statement</span><textarea className="input textarea" rows={3} value={statement} onChange={e=>setStatement(e.target.value)} placeholder="Capture the actual words." /></label><label className="field-label"><span>What I think it means</span><textarea className="input textarea" rows={3} value={meaning} onChange={e=>setMeaning(e.target.value)} placeholder="Hypothesis only — not fact." /></label><label className="field-label"><span>Diagnostic question</span><textarea className="input textarea" rows={3} value={question} onChange={e=>setQuestion(e.target.value)} /></label><label className="field-label"><span>Buyer answer / evidence</span><textarea className="input textarea" rows={3} value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Record what the buyer actually says." /></label></div></section>
  <section className="card resource-section"><div className="eyebrow">CLARIFY → ANSWER → CONFIRM</div><div className="resource-grid"><label className="field-label"><span>Actual barrier</span><textarea className="input textarea" rows={3} value={barrier} onChange={e=>setBarrier(e.target.value)} /></label><label className="field-label"><span>Response</span><textarea className="input textarea" rows={3} value={response} onChange={e=>setResponse(e.target.value)} placeholder="Answer the actual barrier, not the assumed objection." /></label><label className="field-label"><span>Confirmation</span><textarea className="input textarea" rows={3} value={confirmation} onChange={e=>setConfirmation(e.target.value)} /></label><label className="field-label"><span>Next step</span><textarea className="input textarea" rows={3} value={nextStep} onChange={e=>setNextStep(e.target.value)} placeholder="Concrete next action or clear decision." /></label></div><div className="result-block" style={{marginTop:18}}><small className="muted">ROUTING</small><div className="result-stage">{derived}</div></div></section>
  <section className="card resource-section"><div className="eyebrow">SELECTED SCENARIO GUIDE</div><div className="resource-grid"><article className="resource-card"><small className="muted">POSSIBLE MEANING</small><p>{s[1]}</p></article><article className="resource-card"><small className="muted">DIAGNOSTIC QUESTION</small><p>“{s[2]}”</p></article><article className="resource-card"><small className="muted">WHAT TO CLARIFY</small><p>{s[3]}</p></article><article className="resource-card"><small className="muted">RESPONSE / EVIDENCE</small><p>{s[4]}</p></article><article className="resource-card"><small className="muted">CONFIRM</small><p>“{s[5]}”</p></article><article className="resource-card"><small className="muted">NEXT STEP</small><p>{s[6]}</p></article></div></section>
  <section className="card"><div className="eyebrow">BROS GUARDRAILS</div><div className="resource-grid">{["Diagnose sebelum menjawab.","Jangan assume maksud objection.","Jangan beri diskaun untuk menyelesaikan masalah yang belum dikenal pasti.","Jangan fabricate proof, urgency atau scarcity.","Respect clear No.","Silence selepas quotation bukan bukti pasti rejection."].map(x=><div className="resource-card" key={x}><p>☐ {x}</p></div>)}</div><p className="muted" style={{marginTop:18}}>Kerangka ini menyokong Step 5–6 dalam BROS Close Path: Decision Barrier → Clarify. Ia bukan sistem close yang berasingan.</p></section>
  <section className="card"><div className="eyebrow">HOW TO USE</div><ol><li>Capture exact words — jangan translate terus kepada “objection”.</li><li>Treat meaning as hypothesis — “Mahal” boleh bermaksud banyak perkara.</li><li>Ask one focused question.</li><li>Answer the actual barrier.</li><li>Confirm sama ada barrier sudah jelas.</li><li>Choose next step — close, follow-up, more information, pause atau graceful exit.</li></ol><p className="muted">Playbook ialah decision aid, bukan collection of rebuttals. Jika isu sebenarnya value, Value Bridge mungkin diperlukan; jika budget, timing, authority atau comparison, jangan paksa Value Bridge sebagai jawapan kepada semua perkara.</p></section>
 </main>
}
