"use client";

import { useMemo, useState } from "react";

const scripts = [
["New inquiry / opening","Open conversation without premature pitching","Terima kasih. Boleh saya faham sedikit — anda sedang cari solution untuk perkara apa sekarang?","[Problem / context]","Move to discovery","If clear mismatch, clarify or exit"],
["Discovery","Understand current situation","Untuk saya cadangkan yang sesuai, boleh saya tahu bagaimana anda urus perkara ini sekarang?","[Current process]","Ask / listen / clarify","If no relevant need, do not force"],
["Qualification","Check fit and readiness","Supaya saya tak cadangkan benda yang tak sesuai, boleh saya tahu [relevant qualification point]?","[Fit / need / timing / authority]","Qualify","If poor fit, graceful exit"],
["Problem clarification","Separate symptom from real problem","Daripada apa yang anda cerita, nampaknya [summary]. Betul begitu, atau ada bahagian lain yang lebih penting?","[Buyer wording]","Diagnose","If unclear, ask one focused question"],
["Value presentation","Bridge problem to outcome","Kalau fokus utama anda ialah [problem], solution ini membantu melalui [mechanism], dengan matlamat [outcome].","[Problem / mechanism / outcome]","Value Bridge","Confirm relevance"],
["“Berapa harga?” — clear scope","Answer clearly when context is sufficient","Untuk [scope], investmentnya RM[amount]. Termasuk [scope / key deliverable].","[Price / scope]","Confirm fit / next step","If scope changes, re-quote"],
["“Berapa harga?” — scope unclear","Get minimum context before pricing","Boleh. Untuk saya beri harga yang tepat, saya perlukan dua perkara: [X] dan [Y]. Boleh saya tahu?","[Minimum variables]","Clarify then quote","Do not over-question"],
["“Mahal.”","Diagnose actual barrier","Saya faham. Bila anda kata mahal, adakah lebih kepada bajet, skop yang anda perlukan, atau perbandingan dengan pilihan lain?","[Actual options]","Diagnose → answer","If buyer declines, respect it"],
["“Nak fikir dulu.”","Identify unresolved issue","Boleh. Supaya saya tak follow up secara rawak, apa perkara utama yang anda masih perlu fikirkan?","[Barrier / decision criterion]","Clarify","If clear no, close loop"],
["“Nak compare.”","Understand decision criteria","Boleh. Apa yang paling penting untuk anda bandingkan — harga, skop, quality, speed atau perkara lain?","[Criteria]","Compare transparently","If no fit, exit"],
["Quotation sent","Confirm receipt / relevance","Saya dah hantar quotation tadi. Bila anda sempat, saya cuma nak pastikan: adakah skop yang saya cadangkan masih menepati apa yang anda perlukan?","[Scope]","Follow-up with purpose","Avoid repeated “any update?”"],
["Quotation silence","Reopen conversation without assumption","Saya nak check semula quotation [reference]. Adakah perkara ini masih relevan untuk anda, atau timing sudah berubah?","[Reference / trigger]","Diagnose status","If no response after appropriate attempts, stop"],
["Decision maker needed","Map authority","Siapa lagi yang perlu terlibat sebelum keputusan boleh dibuat? Jika perlu, saya boleh bantu sediakan maklumat yang mereka perlukan.","[Stakeholder]","Include / support stakeholder","Do not bypass authority"],
["“Bukan sekarang.”","Clarify timing / trigger","Faham. Apa yang biasanya akan menentukan masa yang lebih sesuai untuk anda?","[Trigger / timing]","Set relevant re-entry point","If no future relevance, close loop"],
["Direct close","Confirm decision when ready","Kalau semua yang kita bincangkan sudah jelas, adakah anda mahu kita teruskan?","Confirm decision + next step","Respect No / Not Now",""],
["Choice close","Help choose between legitimate options","Untuk keadaan anda, saya nampak dua pilihan: [A] dan [B]. Anda lebih cenderung kepada yang mana?","[Options]","Confirm selection","Only when both options are legitimate"],
["Conditional close","Tie decision to real condition","Kalau [condition] sudah jelas/selesai, adakah anda selesa untuk kita teruskan?","[Condition]","Resolve condition","Do not manufacture condition"],
["More information requested","Clarify exact information needed","Boleh. Bahagian mana yang anda mahu saya jelaskan supaya anda boleh buat keputusan dengan lebih yakin?","[Topic]","Provide relevant information","Avoid information dumping"],
["Post-purchase recap","Confirm expectations","Terima kasih. Untuk pastikan semuanya jelas, kita akan buat [scope], dengan next step [action] pada [timing].","[Scope / action / timing]","Operate delivery","If details change, update record"],
["Referral request","Ask after relevant result / value","Jika anda rasa solution ini memang membantu, ada sesiapa dalam network anda yang mungkin sedang menghadapi isu yang sama?","[Relevant audience]","Referral","Do not pressure"],
["Repeat / second sale","Re-enter based on legitimate need","Selepas [result / period], saya nak check sama ada ada keperluan seterusnya yang berkaitan dengan [context].","[Trigger / result]","Diagnose new need","If no need, stop"],
["Reactivation","Reopen old lead with relevance","Kita pernah bincang tentang [problem] sebelum ini. Saya nak check sama ada perkara itu masih relevan, atau keadaan anda sudah berubah?","[Previous context]","Requalify","If irrelevant, close loop"],
["Graceful exit","Respect clear mismatch / no","Faham. Terima kasih kerana beritahu. Saya tak akan paksa. Jika keadaan berubah dan anda perlukan bantuan, anda boleh hubungi saya semula.","Close loop","Do not continue pressure",""]
] as const;

const qa=["Adakah mesej ini ada satu tujuan yang jelas?","Adakah ia menggunakan context conversation sebenar?","Adakah mesej terlalu panjang untuk tindakan yang diperlukan?","Adakah soalan benar-benar diperlukan?","Adakah next move jelas kepada buyer?","Adakah mesej menghormati pilihan buyer?"];

export default function WhatsAppScriptVaultPage(){
 const [selected,setSelected]=useState(0);
 const [context,setContext]=useState("");
 const [custom,setCustom]=useState("");
 const [qaState,setQaState]=useState<boolean[]>([]);
 const s=scripts[selected];
 const rendered=useMemo(()=>custom||s[2], [custom,s]);
 return <main className="container" style={{padding:"28px 0 60px"}}>
  <header className="app-header"><div><div className="brand" style={{fontSize:24}}>BROS SELL™</div><div className="muted">WhatsApp Script Vault</div></div><div style={{display:"flex",gap:8}}><a className="btn secondary" href="/app">Analyzer</a><a className="btn secondary" href="/app/resources">Resources</a></div></header>
  <section className="hero"><p className="muted">OPEN → DISCOVER → QUALIFY → PRESENT → DECIDE → FOLLOW-UP</p><h1>WhatsApp Script Vault</h1><p className="muted hero-copy">Scenario-based swipe file. Adapt to context; do not send scripts mechanically.</p></section>
  <section className="card resource-section"><div className="eyebrow">SCENARIO LIBRARY</div><div className="resource-grid">{scripts.map((x,i)=><button type="button" className={selected===i?"resource-card refined":"resource-card"} key={x[0]} onClick={()=>{setSelected(i);setCustom("");}}><small className="muted">{String(i+1).padStart(2,"0")}</small><h2>{x[0]}</h2><p className="muted">{x[1]}</p></button>)}</div></section>
  <section className="card resource-section"><div className="eyebrow">SELECTED PATTERN</div><div className="resource-grid"><article className="resource-card"><small className="muted">PURPOSE</small><p>{s[1]}</p></article><article className="resource-card"><small className="muted">SUGGESTED SCRIPT</small><p>“{s[2]}”</p></article><article className="resource-card"><small className="muted">PERSONALISE / REPLACE</small><p>{s[3]}</p></article><article className="resource-card"><small className="muted">NEXT MOVE</small><p>{s[4]}</p></article><article className="resource-card"><small className="muted">STOP / EXIT</small><p>{s[5]||"Respect the decision and context."}</p></article></div></section>
  <section className="card resource-section"><div className="eyebrow">ADAPT BEFORE SENDING</div><div className="resource-grid"><label className="field-label"><span>Conversation context</span><textarea className="input textarea" rows={4} value={context} onChange={e=>setContext(e.target.value)} placeholder="Paste or summarise the relevant context." /></label><label className="field-label"><span>Your adapted message</span><textarea className="input textarea" rows={5} value={custom} onChange={e=>setCustom(e.target.value)} placeholder={s[2]} /></label></div><div className="result-block" style={{marginTop:18}}><small className="muted">MESSAGE PREVIEW</small><div className="result-stage" style={{whiteSpace:"pre-wrap"}}>{rendered}</div></div></section>
  <section className="card resource-section"><div className="eyebrow">“BERAPA HARGA?” RULE</div><div className="resource-grid"><div className="resource-card"><h2>Scope jelas → jawab</h2><p>Untuk [scope], investmentnya RM[amount]. Termasuk [scope / key deliverable].</p></div><div className="resource-card"><h2>Scope bergantung pada variables → clarify minimum context</h2><p>Untuk saya beri harga yang tepat, saya perlukan dua perkara: [X] dan [Y]. Boleh saya tahu?</p></div></div><p className="muted" style={{marginTop:18}}>Jangan jadikan harga sebagai jawapan pertama apabila konteks belum jelas.</p></section>
  <section className="card resource-section"><div className="eyebrow">WHATSAPP MESSAGE QA</div><div className="resource-grid">{qa.map((q,i)=><label className="resource-card" key={q}><span style={{display:"flex",gap:10,alignItems:"flex-start"}}><input type="checkbox" checked={Boolean(qaState[i])} onChange={e=>setQaState(p=>{const n=[...p];n[i]=e.target.checked;return n;})}/><span>{q}</span></span></label>)}</div></section>
  <section className="card resource-section"><div className="eyebrow">HOW TO USE</div><div className="resource-grid">{["Use scripts as patterns — script ialah contoh struktur dan wording, bukan ayat wajib.","Personalise context — gantikan bracket dengan maklumat sebenar daripada conversation.","One-message purpose — satu mesej sebaiknya mempunyai satu tujuan utama.","Follow the state — gunakan script yang sesuai dengan lead state dan decision context.","Stop when appropriate — clear No, mismatch atau repeated non-engagement tidak memerlukan pressure."].map(x=><div className="resource-card" key={x}><p>{x}</p></div>)}</div></section>
  <section className="card"><div className="eyebrow">FAILURE MODE</div><p className="muted">Kerangka ini gagal apabila seller copy-paste skrip tanpa context, menghantar terlalu banyak mesej, menggunakan soalan yang tidak perlu, atau menjadikan follow-up sebagai pressure.</p></section>
 </main>
}
