import { createHash } from 'node:crypto';

// Editorial seeds: educational illustrations, never claimed to be customer evidence.
// A seed is retired after one cross-platform package. No automatic recycling.
const rows = [
 ['value','harga-diam','Dah beri harga. Kenapa dia senyap?','Diam belum cukup untuk tahu sebabnya. Mungkin masa belum sesuai atau tawaran belum jelas.','Semak keperluan sebelum ulang harga.','Ada bahagian tawaran yang masih belum jelas, atau masa sekarang belum sesuai?','Tanya untuk faham. Beri ruang untuk jawab.'],
 ['buyer','semua-orang','Produk untuk semua orang?','Sasaran terlalu luas menyukarkan penerangan. Keperluan orang berbeza.','Pilih satu kumpulan dengan satu keperluan nyata.','Siapa paling perlukan penyelesaian ini, dan dalam keadaan apa?','Sasaran yang jelas membantu mesej jadi khusus.'],
 ['offer','senarai-ciri','Banyak ciri. Pelanggan masih keliru.','Senarai ciri belum menerangkan kegunaan dalam situasi pelanggan.','Sambungkan satu ciri kepada satu kegunaan yang relevan.','Untuk keperluan ini, ciri ini membantu dengan cara berikut...','Terangkan kegunaan sebelum tambah maklumat.'],
 ['qualify','cepat-close','Baru bertanya. Terus minta bayar?','Minat awal belum membuktikan tawaran sesuai.','Semak keperluan dan masa penggunaan dahulu.','Apa yang anda mahu selesaikan, dan bila anda perlukan?','Kesesuaian mendahului keputusan membeli.'],
 ['follow-up','follow-up-malu','Nak buat susulan, tapi rasa mengganggu.','Susulan boleh membantu jika ada sebab dan ruang untuk menolak.','Minta izin dan tetapkan masa yang dipersetujui.','Boleh saya hubungi semula pada hari Khamis untuk semak keputusan?','Susulan dengan izin lebih jelas tujuannya.'],
 ['target','target-besar','Sasaran jualan besar. Langkah hari ini kabur.','Angka sasaran perlu dihubungkan dengan tindakan yang boleh dibuat.','Pecahkan sasaran kepada aktiviti dan semak anggaran dengan data sebenar.','Berapa perbualan yang mampu saya urus dengan baik minggu ini?','Anggaran ialah titik mula, bukan jaminan hasil.'],
 ['lead','banyak-enquiry','Ramai bertanya. Semua perlu dilayan sama?','Jumlah pertanyaan tidak sama dengan keperluan atau kesediaan membeli.','Catat keperluan, masa dan tindakan seterusnya setiap lead.','Apa keperluannya, bila diperlukan, dan apa langkah seterusnya?','Utamakan berdasarkan bukti, bukan andaian.'],
 ['close','nak-fikir','Pelanggan kata: Saya fikir dulu.','Mungkin ada perkara untuk disemak. Jangan terus anggap alasan.','Tanya perkara yang masih perlu dipertimbangkan.','Ada perkara tertentu yang anda mahu semak sebelum membuat keputusan?','Bantu keputusan tanpa mendesak jawapan.'],
 ['multiply','lepas-bayar','Pelanggan dah bayar. Perbualan tamat?','Pembelian memerlukan langkah serahan yang jelas.','Nyatakan apa yang diterima dan tindakan selepas bayaran.','Ini langkah seterusnya dan cara mendapatkan bantuan jika perlu.','Serahan yang jelas ialah sebahagian cara menjual.'],
 ['operate','ingat-semua','Semua maklumat pelanggan dalam kepala.','Ingatan mudah tercicir apabila perbualan bertambah.','Simpan catatan ringkas fakta dan tindakan seterusnya.','Keperluan, status, tindakan seterusnya, tarikh susulan.','Catat yang perlu. Hormati privasi pelanggan.'],
 ['value','mahal','Pelanggan kata: Mahal.','Harga mungkin berkait dengan bajet, perbandingan atau kesesuaian.','Kenal pasti maksud mahal sebelum ubah tawaran.','Adakah ia di luar bajet, atau anda sedang bandingkan pilihan lain?','Satu perkataan boleh membawa sebab berbeza.'],
 ['buyer','masalah-sebenar','Dia tanya produk. Anda tahu keperluannya?','Nama produk yang ditanya belum menerangkan masalah yang mahu diselesaikan.','Tanya cara penggunaan yang diharapkan.','Anda mahu gunakan ini untuk situasi yang bagaimana?','Fahami penggunaan sebelum cadangkan pilihan.'],
 ['offer','pakej-terlalu-banyak','Terlalu banyak pakej. Susah nak pilih.','Pilihan yang banyak boleh menambah kerja membuat perbandingan.','Bandingkan pilihan pada perkara yang relevan sahaja.','Bezanya pada skop, kegunaan dan jumlah bayaran.','Jelaskan perbezaan, bukan sekadar nama pakej.'],
 ['qualify','bajet','Nak tanya bajet tanpa rasa janggal.','Bajet membantu semak kesesuaian, bukan menilai kemampuan seseorang.','Terangkan sebab soalan sebelum bertanya.','Supaya saya cadangkan pilihan sesuai, ada julat bajet yang anda selesa?','Hormati julat dan pilihan pelanggan.'],
 ['follow-up','dah-check','Setiap susulan cuma: Dah semak?','Mesej yang sama mungkin tidak membantu pertimbangan pelanggan.','Bawa maklumat yang menjawab perkara belum jelas.','Ini ringkasan perbezaan yang kita bincang. Ada yang perlu dijelaskan?','Susulan perlu membawa nilai, bukan tekanan.'],
 ['target','aktiviti-hasil','Sibuk setiap hari. Apa yang bergerak?','Aktiviti yang banyak belum menunjukkan kemajuan yang sama.','Bezakan aktiviti dibuat dengan hasil yang diperhatikan.','Berapa pertanyaan, perbualan sesuai dan keputusan sebenar minggu ini?','Semak kemajuan dengan fakta.'],
 ['lead','mesej-pertama','Tak tahu nak mula perbualan jualan.','Pembukaan yang jelas boleh bermula dengan sebab orang menghubungi anda.','Rujuk pertanyaan sebenar dan tanya satu soalan relevan.','Terima kasih bertanya. Untuk kegunaan apa anda perlukan pilihan ini?','Mulakan dengan konteks, bukan skrip panjang.'],
 ['close','minta-keputusan','Bagaimana nak tanya keputusan dengan sopan?','Pelanggan perlukan pilihan yang jelas, termasuk ruang untuk belum bersedia.','Ringkaskan tawaran dan beri pilihan langkah seterusnya.','Jika sesuai, kita boleh teruskan. Jika belum, apa yang perlu anda semak?','Jemput keputusan dengan maklumat yang cukup.'],
 ['multiply','minta-referral','Bila sesuai minta rujukan pelanggan?','Rujukan patut diminta dengan izin selepas pengalaman dapat disemak.','Tanya pengalaman dahulu. Jangan anggap pelanggan berpuas hati.','Bagaimana pengalaman anda? Jika sesuai, boleh kongsikan kepada yang memerlukan.','Rujukan ialah pilihan pelanggan.'],
 ['operate','lead-tercicir','Ada pelanggan yang terlupa dibalas.','Perbualan tanpa tindakan seterusnya mudah hilang daripada perhatian.','Semak senarai perbualan terbuka pada waktu tetap.','Siapa menunggu jawapan, dan apa yang saya perlu buat?','Tutup gelung perbualan, bukan hanya tab mesej.'],
 ['value','diskaun-awal','Belum faham keperluan. Dah beri diskaun.','Harga lebih rendah tidak semestinya menjawab kekeliruan tawaran.','Jelaskan skop dan kesesuaian sebelum bincang pilihan harga.','Bahagian mana paling penting untuk keperluan anda?','Jangan ubah harga kerana andaian.'],
 ['buyer','andaian-motif','Dia lambat balas. Betulkah tak berminat?','Kelajuan membalas tidak cukup untuk menentukan niat seseorang.','Pisahkan apa yang berlaku daripada tafsiran anda.','Fakta: belum dibalas. Sebab: belum diketahui.','Jangan jadikan tafsiran sebagai fakta.'],
 ['offer','tidak-termasuk','Apa yang tidak termasuk dalam tawaran?','Batas tawaran membantu pelanggan mengelakkan jangkaan yang salah.','Nyatakan skop, batas dan caj tambahan yang benar-benar terpakai.','Pakej ini termasuk perkara berikut. Bahagian ini tidak termasuk.','Batas yang jelas mengurangkan salah faham.'],
 ['qualify','siapa-putuskan','Dia perlu bincang dengan orang lain.','Keputusan boleh melibatkan orang lain. Hormati proses itu.','Tanya maklumat yang diperlukan untuk perbincangan.','Apa maklumat yang boleh saya ringkaskan untuk perbincangan anda?','Bantu proses keputusan, bukan pintasnya.'],
 ['follow-up','masa-salah','Susulan pada masa yang tidak sesuai.','Masa susulan perlu mengikut keperluan dan izin, bukan desakan penjual.','Semak waktu yang pelanggan selesa.','Bila waktu yang sesuai untuk saya hubungi semula?','Tetapkan masa bersama, bukan secara sepihak.'],
 ['target','nombor-agak','Berapa jualan yang realistik bulan ini?','Sasaran memerlukan andaian yang boleh diuji dan kapasiti sebenar.','Mulakan daripada data terbaru dan kapasiti serahan.','Apakah asas angka ini, dan apa yang perlu disemak minggu depan?','Ubah anggaran apabila bukti berubah.'],
 ['lead','saluran-berbeza','Pelanggan datang dari mana?','Tanpa catatan sumber, sukar tahu saluran yang membawa pertanyaan sesuai.','Catat sumber yang diketahui tanpa meneka.','Dari mana anda tahu tentang tawaran ini?','Belajar daripada sumber lead yang sebenar.'],
 ['close','bayaran-jelas','Nak teruskan. Cara bayaran jelas?','Keputusan membeli perlu diikuti arahan yang mudah disemak.','Nyatakan jumlah, kaedah dan proses pengesahan yang sebenar.','Ini jumlah bayaran dan langkah pengesahan selepas pembayaran.','Maklumat bayaran perlu telus.'],
 ['multiply','repeat-order','Nak pelanggan kembali tanpa memaksa.','Keperluan berulang tidak sama bagi setiap pelanggan.','Semak sama ada keperluan seterusnya memang wujud.','Adakah anda perlukan perkara ini lagi nanti, dan mahu dihubungi semula?','Jualan berulang bermula dengan keperluan sebenar.'],
 ['operate','semak-mingguan','Nak baiki jualan. Mula dari mana?','Cuba ubah semuanya serentak menyukarkan pembelajaran.','Pilih satu masalah daripada rekod perbualan minggu ini.','Di bahagian mana perbualan paling kerap berhenti?','Uji satu perubahan. Semak apa yang berlaku.'],
 ['value','banding-harga','Dia banding dengan pilihan lebih murah.','Perbandingan perlu mengambil kira skop dan kesesuaian yang sebenar.','Bandingkan secara adil tanpa merendahkan pesaing.','Mari semak apa yang termasuk dalam setiap pilihan.','Jelaskan beza yang boleh dibuktikan.'],
 ['buyer','guna-bahasa','Penerangan betul, tapi terlalu teknikal.','Istilah dalaman mungkin tidak biasa kepada pelanggan.','Ganti satu istilah dengan contoh kegunaan mudah.','Maksudnya, anda boleh gunakan ini untuk langkah berikut...','Bantu orang faham sebelum tambah istilah.'],
 ['offer','satu-ayat','Boleh jelaskan tawaran dalam satu ayat?','Penerangan ringkas memerlukan keperluan, penyelesaian dan batas yang jelas.','Tulis siapa dibantu dan kerja yang tawaran membantu lakukan.','Ini membantu kumpulan ini melakukan kerja ini melalui bahan ini.','Ringkas perlu tetap tepat.'],
 ['qualify','tidak-sesuai','Bagaimana jika produk anda tak sesuai?','Keperluan pelanggan boleh berada di luar skop tawaran.','Jelaskan batas dan cadangkan semakan pilihan yang lebih sesuai.','Untuk keperluan itu, tawaran saya mungkin tidak mencukupi.','Kejujuran ialah sebahagian cara menjual.'],
 ['follow-up','bila-berhenti','Berapa kali patut buat susulan?','Tiada angka tunggal yang sesuai untuk semua hubungan dan keadaan.','Ikut izin, konteks dan respons. Berhenti apabila diminta.','Jika anda belum perlukan, saya boleh hentikan susulan buat masa ini.','Hormati penolakan dan ruang pelanggan.'],
 ['target','kapasiti','Banyak permintaan. Mampu tunaikan?','Sasaran perlu selari dengan kapasiti menyiapkan kerja.','Semak masa, stok dan sokongan sebelum menerima komitmen.','Berapa tempahan boleh disiapkan mengikut janji yang diberi?','Janji perlu berpijak pada kapasiti.'],
 ['lead','balas-harga','Pelanggan tanya harga. Jawab berbelit?','Soalan harga patut dijawab jelas. Soalan lanjut boleh menyemak kesesuaian.','Beri harga yang benar dahulu, kemudian semak konteks.','Harganya seperti berikut. Untuk kegunaan apa anda perlukan?','Jangan tahan jawapan untuk memaksa perbualan.'],
 ['close','belum-bersedia','Pelanggan belum bersedia membeli.','Belum bersedia bukan izin untuk menambah tekanan.','Tanya sama ada mahu maklumat atau susulan pada masa lain.','Anda mahu saya ringkaskan maklumat dahulu, atau hentikan di sini?','Pembeli berhak memilih masa dan keputusan.'],
 ['multiply','maklum-balas','Nak maklum balas yang boleh digunakan.','Soalan terlalu umum mungkin tidak menunjukkan perkara yang perlu diperbaiki.','Tanya satu bahagian pengalaman secara khusus.','Bahagian mana yang jelas, dan bahagian mana yang mengelirukan?','Dengar pengalaman sebelum cadangkan pembaikan.'],
 ['operate','skrip-kaku','Skrip sama untuk semua pelanggan?','Skrip ialah panduan. Konteks perbualan tetap perlu difahami.','Ambil tujuan soalan dan sesuaikan dengan fakta pelanggan.','Apakah yang saya perlu faham sebelum memilih respons?','Faham tujuan, kemudian pilih ayat.'],
 ['value','bukti','Nak tunjuk bukti tanpa berlebihan.','Bukti perlu sesuai dengan dakwaan dan boleh disemak.','Tunjuk bahan atau proses sebenar. Nyatakan batasnya.','Ini contoh bahan yang diterima, bukan jaminan hasil jualan.','Bukti produk berbeza daripada janji hasil.'],
 ['buyer','dengar','Anda bercakap lebih banyak daripada bertanya?','Penerangan panjang boleh terlepas maklumat penting daripada pelanggan.','Tanya satu soalan dan beri ruang untuk jawapan.','Apa perkara paling penting untuk anda dalam pilihan ini?','Jawapan pelanggan membantu arah penerangan.'],
 ['offer','janji','Ayat tawaran anda menjanjikan apa?','Janji yang terlalu luas boleh mencipta jangkaan yang tidak mampu ditunaikan.','Semak setiap janji dengan skop dan bukti sebenar.','Adakah saya boleh membuktikan dan menunaikan ayat ini?','Jual dengan janji yang boleh dipertanggungjawabkan.'],
 ['qualify','masa-perlu','Bila pelanggan perlukan penyelesaian?','Masa keperluan membantu semak kesediaan dan kapasiti serahan.','Tanya tarikh atau keadaan penggunaan tanpa mencipta urgensi.','Bila anda bercadang gunakan ini?','Masa pelanggan ialah konteks, bukan alat tekanan.'],
 ['follow-up','selepas-maklumat','Dah hantar maklumat. Apa langkah seterusnya?','Maklumat tanpa langkah seterusnya boleh meninggalkan kedua-dua pihak kabur.','Setuju tindakan kecil selepas pelanggan semak.','Selepas semak, adakah anda mahu saya jawab perkara yang belum jelas?','Arah perbualan perlu dipersetujui.'],
 ['target','keutamaan','Banyak kerja jualan. Mana satu dahulu?','Keutamaan perlu mengambil kira perkara yang benar-benar menunggu tindakan.','Dahulukan janji, jawapan tertangguh dan lead yang sesuai.','Tindakan mana membantu menyelesaikan keperluan yang sudah jelas?','Keutamaan berpandukan konteks dan tanggungjawab.'],
 ['lead','lead-bukan-nombor','Nama pelanggan ada. Keperluan tak dicatat.','Senarai kontak sahaja belum menjadi rekod perbualan yang berguna.','Catat fakta yang pelanggan beri dan elakkan label spekulatif.','Apa yang diminta, apa yang dijawab, dan apa yang dipersetujui?','Rekod membantu kesinambungan, bukan meneka niat.'],
 ['close','ringkas-sebelum-bayar','Sebelum bayar, semak fahaman bersama.','Persetujuan perlu berpandukan tawaran yang kedua-dua pihak faham.','Ringkaskan skop, bayaran dan serahan sebelum meminta pengesahan.','Adakah ringkasan ini sama dengan apa yang anda perlukan?','Pastikan jelas sebelum teruskan.'],
 ['multiply','bantuan','Pelanggan perlukan bantuan selepas membeli.','Cara mendapatkan bantuan perlu mudah dikenal pasti.','Berikan saluran dan proses bantuan yang memang tersedia.','Jika ada bahagian yang kurang jelas, ini saluran bantuan yang boleh digunakan.','Sokongan yang jelas melengkapkan serahan.'],
 ['operate','gagal-belajar','Perbualan tak jadi jualan. Apa yang dipelajari?','Tidak membeli tidak semestinya membuktikan satu sebab tertentu.','Catat sebab yang dinyatakan. Tandakan perkara yang belum diketahui.','Apa bukti yang ada, dan apa yang masih andaian?','Belajar tanpa mereka-reka sebab.'],
 ['value','hasil-bukan-ciri','Apa kaitan tawaran dengan kerja pelanggan?','Pelanggan mungkin perlukan penerangan tentang penggunaan, bukan tambahan ciri.','Jelaskan satu kerja yang bahan membantu lakukan, dengan batasnya.','Bahan ini membantu anda menyusun langkah ini. Hasil bergantung pada pelaksanaan.','Terangkan bantuan secara konkrit.'],
 ['buyer','baharu-lama','Pelanggan baharu dan lama perlukan maklumat sama?','Pengetahuan sedia ada berbeza. Jangan anggap kedua-duanya sama.','Semak apa yang sudah diketahui dan perkara yang mahu dipastikan.','Apa yang anda sudah tahu, dan bahagian mana mahu saya jelaskan?','Sesuaikan penerangan dengan kefahaman sebenar.'],
 ['offer','jumlah-bayaran','Harga asas ada. Jumlah akhir jelas?','Pelanggan perlu tahu jumlah yang benar-benar perlu dibayar.','Semak semua caj terpakai sebelum menyatakan jumlah akhir.','Ini jumlah akhir berdasarkan skop yang kita setuju.','Ketelusan harga mengelakkan kejutan.'],
 ['qualify','pilihan-sesuai','Cadangan berdasarkan apa?','Cadangan yang baik mempunyai sebab daripada keperluan pelanggan.','Hubungkan cadangan dengan fakta yang pelanggan nyatakan.','Berdasarkan penggunaan ini, pilihan ini mungkin lebih sesuai kerana...','Nyatakan sebab dan batas cadangan.'],
 ['follow-up','ubah-keputusan','Pelanggan ubah keputusan selepas susulan.','Keadaan pelanggan boleh berubah. Semak konteks terbaru.','Tanya perubahan keperluan sebelum menawarkan semula.','Adakah keperluan atau masa anda sudah berubah sejak perbualan lalu?','Kemas kini fakta sebelum ambil tindakan.'],
 ['target','satu-ujian','Nak cuba cara jualan baharu. Uji apa?','Tanpa satu fokus, sukar tahu perubahan mana yang membantu.','Uji satu cara menerangkan nilai pada kumpulan yang relevan.','Apakah respons sebenar sebelum dan selepas perubahan ini?','Ujian kecil memerlukan catatan yang jelas.'],
 ['lead','serah-lead','Orang lain sambung perbualan pelanggan.','Maklumat penting mudah hilang semasa serahan kerja.','Serahkan fakta, janji dan tindakan seterusnya dengan izin yang sesuai.','Ini permintaan, jawapan dan perkara yang sudah dipersetujui.','Serahan perlu tepat dan menjaga privasi.'],
 ['close','pilihan-tidak','Bagaimana menjawab pelanggan yang menolak?','Penolakan ialah keputusan pelanggan, bukan cabaran untuk ditewaskan.','Terima dengan sopan. Tanya maklum balas hanya jika sesuai dan diizinkan.','Terima kasih memaklumkan. Saya hormati keputusan anda.','Hormati keputusan tanpa menyindir.'],
 ['multiply','janji-serahan','Janji serahan berubah. Apa perlu dibuat?','Perubahan perlu dijelaskan sebelum pelanggan terus menunggu tanpa berita.','Maklumkan keadaan sebenar dan pilihan yang tersedia.','Ini perubahan yang berlaku dan pilihan yang boleh kita semak.','Jangan sembunyikan perubahan yang relevan.'],
 ['operate','sistem-ringkas','Perlu sistem rumit untuk mula menjual?','Cara kerja boleh bermula dengan rekod ringkas yang digunakan secara konsisten.','Mulakan dengan satu senarai keperluan, status dan tindakan.','Bolehkah saya tahu langkah seterusnya bagi setiap perbualan?','Sistem berguna apabila membantu tindakan sebenar.']
];

export const catalog = rows.map(([stage,id,hook,reframe,step,question,lesson]) => ({stage,id,hook,reframe,step,question,lesson}));
export const hash = value => createHash('sha256').update(typeof value === 'string' ? value : JSON.stringify(value)).digest('hex');
export const normalize = text => text.normalize('NFKC').replace(/\s+/g,' ').trim().toLowerCase();

export function packageFor(seed, index, config) {
  const illustrated = 'Contoh situasi jualan, bukan kisah pelanggan.';
  const educational = `${seed.hook}\n\n${illustrated}\n\n${seed.reframe}\n\nCuba langkah ini: ${seed.step}\n\nContoh ayat / soalan:\n“${seed.question}”\n\n${seed.lesson}\n\nMenjelaskan, bukan Memujuk.`;
  const product = index % 5 === 4;
  const cta = product ? '\n\nBROS SELL™ — Panduan & Alat Jualan Praktikal. Bantu susun cara menjual dengan lebih jelas dan teratur.' : '\n\nSimpan untuk rujukan perbualan seterusnya.';
  const captions = {
    facebook: educational + cta + (product ? `\nKenali BROS SELL™: ${config.landingUrl}` : ''),
    instagram: educational + cta + '\n\n#BROSSell #Jualan #PeniagaMalaysia',
    tiktok: `${seed.hook}\n\n${illustrated}\n\n${seed.reframe}\n\n${seed.step}\n\n“${seed.question}”\n\n${seed.lesson}\n\nMenjelaskan, bukan Memujuk.` + cta + '\n\n#BROSSell #Jualan #PeniagaMalaysia'
  };
  for (const [service,text] of Object.entries(captions)) validateCaption(text,service);
  return {id:seed.id,stage:seed.stage,promotional:product,contentHash:hash(normalize(educational)),seed,captions};
}

export function validateCaption(text, service) {
  const max = {facebook:5000,instagram:2200,tiktok:2200}[service];
  if (!max || [...text].length > max) throw new Error(`Caption limit: ${service}`);
  if ((text.match(/#[\p{L}\p{N}_]+/gu) || []).length > 5) throw new Error('Hashtag limit');
  if (/RM\s*(?:50|99|399)\b|30.day|30 hari.*(?:jamin|refund)|guaranteed|pasti berjaya|testimoni|first 100|early bird|lifetime/iu.test(text)) throw new Error('Unapproved commercial claim');
  if (!text.includes('Menjelaskan, bukan Memujuk.')) throw new Error('Doctrine missing');
}
